FROM golang:alpine3.21 AS build
WORKDIR /build
COPY . .
RUN CGO_ENABLE=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:3.21 AS app
WORKDIR /app
COPY --from=build /build/main .
CMD [ "./main" ]


